# Generated by Django 6.0.1 on 2026-01-30 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_staff_created_at_remove_staff_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='contact',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='functional_area',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
