# Generated by Django 6.0.1 on 2026-01-30 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_staff_contact_alter_staff_functional_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='contact',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
