# Generated by Django 6.0.1 on 2026-02-02 06:44

import django.db.models.deletion
import simple_history.models
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_staff_contact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Information'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], db_index=True, max_length=20)),
                ('message', models.TextField()),
                ('module', models.CharField(db_index=True, max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('exception_trace', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='staff',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='device_model',
            field=models.CharField(blank=True, help_text='Device model', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='device_registered_at',
            field=models.DateTimeField(blank=True, help_text='When the device was registered', null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is this account active?'),
        ),
        migrations.AddField(
            model_name='staff',
            name='registered_device_id',
            field=models.CharField(blank=True, help_text='Device ID registered to this staff member', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='contact',
            field=models.CharField(default='gtime', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staff',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='staff_photos/', validators=[users.models.validate_photo_size]),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_contact', models.CharField(db_index=True, max_length=15)),
                ('action', models.CharField(choices=[('LOGIN', 'Login Attempt'), ('LOGIN_SUCCESS', 'Successful Login'), ('LOGIN_FAILED', 'Failed Login'), ('SCAN', 'QR Scan'), ('LOGOUT', 'Logout'), ('DEVICE_REGISTER', 'Device Registration'), ('DEVICE_CHANGE_ATTEMPT', 'Unauthorized Device Attempt'), ('PHOTO_UPDATE', 'Photo Updated'), ('DATA_UPDATE', 'Staff Data Updated')], db_index=True, max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('device_id', models.CharField(blank=True, max_length=100, null=True)),
                ('device_model', models.CharField(blank=True, max_length=100, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('success', models.BooleanField(db_index=True, default=True)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='users.staff')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalStaff',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('functional_area', models.CharField(blank=True, max_length=255, null=True)),
                ('staff_id', models.CharField(blank=True, max_length=50, null=True)),
                ('contact', models.CharField(db_index=True, max_length=50)),
                ('photo', models.TextField(blank=True, max_length=100, null=True, validators=[users.models.validate_photo_size])),
                ('registered_device_id', models.CharField(blank=True, help_text='Device ID registered to this staff member', max_length=100, null=True)),
                ('device_registered_at', models.DateTimeField(blank=True, help_text='When the device was registered', null=True)),
                ('device_model', models.CharField(blank=True, help_text='Device model', max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is this account active?')),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical staff',
                'verbose_name_plural': 'historical staffs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
